"""Tests for the agentshore init identity wizard."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
import yaml

if TYPE_CHECKING:
    from pathlib import Path

from agentshore.cli_identity import (
    GhAccount,
    IdentityBinding,
    WizardResult,
    normalize_trusted_ids_for_bound_agents,
    parse_gh_auth_status,
    patch_yaml_with_bindings,
    run_wizard,
)

# ---------------------------------------------------------------------------
# gh auth status parser
# ---------------------------------------------------------------------------


_GH_STATUS_TEXT = """\
github.com
  ✓ Logged in to github.com account example-user (active)
    - Active account: true
    - Git operations protocol: ssh
    - Token: gho_*****
    - Token scopes: 'gist', 'read:org', 'repo'
  ✓ Logged in to github.com account unseriousAI
    - Active account: false
    - Git operations protocol: ssh
    - Token: gho_*****
"""


def test_parse_gh_auth_status_two_accounts() -> None:
    accounts = parse_gh_auth_status(_GH_STATUS_TEXT)
    logins = [a.login for a in accounts]
    assert logins == ["example-user", "unseriousAI"]
    assert accounts[0].active is True
    assert accounts[1].active is False


def test_parse_gh_auth_status_empty() -> None:
    assert parse_gh_auth_status("") == []


def test_parse_gh_auth_status_ignores_other_hosts() -> None:
    text = """\
gitlab.com
  ✓ Logged in to gitlab.com account someone (active)
"""
    assert parse_gh_auth_status(text) == []


# ---------------------------------------------------------------------------
# YAML patcher
# ---------------------------------------------------------------------------


_BASE_YAML = """\
# Auto-generated by AgentShore.  Edit to customise.
project:
  path: .
  goals: null
agents:
  claude_code:
    enabled: true
    binary: claude
  codex:
    enabled: true
    binary: codex
budget:
  enabled: false
  total: 0.00
"""


def test_patcher_writes_identities_and_links_agents(tmp_path: Path) -> None:
    config_path = tmp_path / "agentshore.yaml"
    config_path.write_text(_BASE_YAML, encoding="utf-8")

    result = WizardResult(
        identities={
            "example-user": IdentityBinding(
                name="example-user",
                git_user_name="Wes",
                git_user_email="user@example.com",
                gh_token_login="example-user",
            ),
            "unseriousAI": IdentityBinding(
                name="unseriousAI",
                git_user_name="unseriousAI",
                git_user_email="bot@example.com",
                gh_token_env="UNSERIOUSAI_GH_TOKEN",
            ),
        },
        agent_to_identity={"claude_code": "example-user", "codex": "unseriousAI"},
    )

    assert patch_yaml_with_bindings(config_path, result) is True

    text = config_path.read_text(encoding="utf-8")
    assert text.startswith("# Auto-generated"), "leading comment must be preserved"
    data = yaml.safe_load(text)
    assert data["identities"]["example-user"]["gh_token_login"] == "example-user"
    assert data["identities"]["unseriousai"]["gh_token_env"] == "UNSERIOUSAI_GH_TOKEN"
    assert data["agents"]["claude_code"]["identity"] == "example-user"
    assert data["agents"]["codex"]["identity"] == "unseriousai"
    assert data["trusted_ids"]["github_logins"] == ["example-user", "unseriousai"]
    # Pre-existing keys preserved.
    assert data["budget"]["enabled"] is False


def test_patcher_merges_agent_identities_into_existing_trusted_ids(tmp_path: Path) -> None:
    config_path = tmp_path / "agentshore.yaml"
    config_path.write_text(
        _BASE_YAML
        + """\
trusted_ids:
  github_logins:
    - ExternalUser
    - unseriousai
""",
        encoding="utf-8",
    )

    result = WizardResult(
        identities={
            "unseriousai": IdentityBinding(
                name="unseriousAI",
                git_user_name="unseriousAI",
                git_user_email="bot@example.com",
                gh_token_keychain="agentshore/unseriousAI",
            ),
            "example-user": IdentityBinding(
                name="example-user",
                git_user_name="Wes",
                git_user_email="user@example.com",
                gh_token_login="example-user",
            ),
        },
        agent_to_identity={"claude_code": "example-user", "codex": "unseriousAI"},
    )

    assert patch_yaml_with_bindings(config_path, result) is True

    data = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    assert data["trusted_ids"]["github_logins"] == [
        "externaluser",
        "unseriousai",
        "example-user",
    ]


def test_normalizer_merges_existing_bound_env_identity_not_git_user_name(
    tmp_path: Path,
) -> None:
    config_path = tmp_path / "agentshore.yaml"
    config_path.write_text(
        _BASE_YAML.replace(
            "  codex:\n    enabled: true\n    binary: codex",
            "  codex:\n    enabled: true\n    binary: codex\n    identity: unseriousai",
        )
        + """\
identities:
  unseriousai:
    git_user_name: "Unserious AI Bot"
    git_user_email: bot@example.com
    gh_token_env: UNSERIOUSAI_GH_TOKEN
trusted_ids:
  github_logins:
    - ExternalUser
""",
        encoding="utf-8",
    )

    assert normalize_trusted_ids_for_bound_agents(config_path) is True

    data = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    assert data["trusted_ids"]["github_logins"] == ["externaluser", "unseriousai"]


def test_normalizer_uses_keychain_service_login_not_git_user_name(
    tmp_path: Path,
) -> None:
    config_path = tmp_path / "agentshore.yaml"
    config_path.write_text(
        _BASE_YAML.replace(
            "  codex:\n    enabled: true\n    binary: codex",
            "  codex:\n    enabled: true\n    binary: codex\n    identity: bot",
        )
        + """\
identities:
  bot:
    git_user_name: "Unserious AI Bot"
    git_user_email: bot@example.com
    gh_token_keychain: agentshore/example-user/example-repo/unseriousAI
""",
        encoding="utf-8",
    )

    assert normalize_trusted_ids_for_bound_agents(config_path) is True

    data = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    assert data["trusted_ids"]["github_logins"] == ["unseriousai"]


def test_identity_prefill_uses_configured_login_not_git_user_name(
    tmp_path: Path,
) -> None:
    from agentshore.cli import _existing_identities_from_yaml, _identity_defaults_from_yaml

    config_path = tmp_path / "agentshore.yaml"
    config_path.write_text(
        _BASE_YAML.replace(
            "  codex:\n    enabled: true\n    binary: codex",
            "  codex:\n    enabled: true\n    binary: codex\n    identity: bot",
        )
        + """\
identities:
  bot:
    git_user_name: "Unserious AI Bot"
    git_user_email: bot@example.com
    gh_token_keychain: agentshore/example-user/example-repo/unseriousAI
""",
        encoding="utf-8",
    )

    defaults = _identity_defaults_from_yaml(config_path)
    existing = _existing_identities_from_yaml(config_path)

    assert defaults["codex"] == "unseriousai"
    assert list(existing) == ["unseriousai"]
    assert "unserious ai bot" not in existing


def test_patcher_no_op_when_empty_result(tmp_path: Path) -> None:
    config_path = tmp_path / "agentshore.yaml"
    config_path.write_text(_BASE_YAML, encoding="utf-8")
    result = WizardResult(identities={}, agent_to_identity={})
    assert patch_yaml_with_bindings(config_path, result) is False


def test_patcher_round_trips_via_load_config(tmp_path: Path) -> None:
    """Output of the patcher must load cleanly through load_config."""
    from agentshore.config import load_config

    config_path = tmp_path / "agentshore.yaml"
    config_path.write_text(_BASE_YAML, encoding="utf-8")

    result = WizardResult(
        identities={
            "example-user": IdentityBinding(
                name="example-user",
                git_user_name="Wes",
                git_user_email="user@example.com",
                gh_token_login="example-user",
            )
        },
        agent_to_identity={"claude_code": "example-user"},
    )
    patch_yaml_with_bindings(config_path, result)
    cfg = load_config(config_path)
    assert cfg.identities["example-user"].gh_token_login == "example-user"
    assert cfg.agents["claude_code"].identity == "example-user"


def test_patcher_collapses_duplicate_case_insensitive_identity_keys(tmp_path: Path) -> None:
    """The identity wizard must repair mixed-case duplicate identity keys."""
    from agentshore.config import load_config

    config_path = tmp_path / "agentshore.yaml"
    config_path.write_text(
        _BASE_YAML
        + """\
identities:
  unseriousAI:
    git_user_name: Old Mixed
    git_user_email: old-mixed@example.com
    gh_token_env: OLD_TOKEN
  unseriousai:
    git_user_name: Old Lower
    git_user_email: old-lower@example.com
    gh_token_env: OLD_LOWER_TOKEN
""",
        encoding="utf-8",
    )

    result = WizardResult(
        identities={
            "unseriousai": IdentityBinding(
                name="unseriousai",
                git_user_name="unseriousAI",
                git_user_email="bot@example.com",
                gh_token_keychain="agentshore/unseriousAI",
            )
        },
        agent_to_identity={"codex": "unseriousAI"},
    )

    assert patch_yaml_with_bindings(config_path, result) is True

    data = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    assert list(data["identities"]) == ["unseriousai"]
    assert data["identities"]["unseriousai"]["gh_token_keychain"] == "agentshore/unseriousai"
    assert data["agents"]["codex"]["identity"] == "unseriousai"
    cfg = load_config(config_path)
    assert cfg.identities["unseriousai"].gh_token_keychain == "agentshore/unseriousai"
    assert cfg.agents["codex"].identity == "unseriousai"


# ---------------------------------------------------------------------------
# run_wizard interactive flow
# ---------------------------------------------------------------------------


def test_run_wizard_no_accounts_returns_empty(monkeypatch: pytest.MonkeyPatch) -> None:
    """With no gh accounts the wizard offers (n)/(s); skipping every agent
    yields an empty result."""
    from agentshore import cli_identity as mod

    inputs = iter(["s", "s"])

    def fake_prompt(msg: str, default: str | None = None, **_: object) -> str:
        try:
            value = next(inputs)
        except StopIteration as exc:
            raise AssertionError(f"unexpected prompt: {msg}") from exc
        return value or (default if default is not None else "")

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    result = run_wizard(["claude_code", "codex"], accounts=[])
    assert result.identities == {}
    assert result.agent_to_identity == {}


def test_run_wizard_binds_each_agent(monkeypatch: pytest.MonkeyPatch) -> None:
    """Drive the wizard via stubbed click prompts."""
    from agentshore import cli_identity as mod

    # Two-pass flow:
    #   Pass 1 (mapping):  claude_code → 1 (example-user, default), codex → 2.
    #   Pass 2 (details):  example-user  email "", name "", strategy "1";
    #                      unseriousAI email "", name "", strategy "1".
    inputs = iter(["1", "2", "", "", "1", "", "", "1"])
    confirms: object = iter([])  # gh_token_login takes no confirms

    def fake_prompt(msg: str, default: str | None = None, **_: object) -> str:
        try:
            value = next(inputs)
        except StopIteration as exc:
            raise AssertionError(f"unexpected prompt: {msg}") from exc
        return value or (default if default is not None else "")

    def fake_confirm(_msg: str, default: bool = False, **_kw: object) -> bool:
        try:
            return next(confirms)
        except StopIteration:
            return default

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    monkeypatch.setattr(mod.click, "confirm", fake_confirm)

    accounts = [
        GhAccount(login="example-user", active=True),
        GhAccount(login="unseriousAI", active=False),
    ]
    result = run_wizard(["claude_code", "codex"], accounts=accounts)

    assert result.agent_to_identity == {
        "claude_code": "example-user",
        "codex": "unseriousai",
    }
    assert result.identities["example-user"].gh_token_login == "example-user"
    assert result.identities["unseriousai"].gh_token_login == "unseriousAI"
    assert (
        result.identities["example-user"].git_user_email == "example-user@users.noreply.github.com"
    )


def test_run_wizard_skip_for_one_agent(monkeypatch: pytest.MonkeyPatch) -> None:
    from agentshore import cli_identity as mod

    # Two-pass:
    #   Pass 1: claude_code → 1 (default), codex → 's' (skip)
    #   Pass 2: example-user email "", name "", strategy "1"
    inputs = iter(["1", "s", "", "", "1"])
    confirms: object = iter([])

    def fake_prompt(msg: str, default: str | None = None, **_: object) -> str:
        try:
            value = next(inputs)
        except StopIteration as exc:
            raise AssertionError(f"unexpected prompt: {msg}") from exc
        return value or (default if default is not None else "")

    def fake_confirm(_msg: str, default: bool = False, **_kw: object) -> bool:
        try:
            return next(confirms)
        except StopIteration:
            return default

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    monkeypatch.setattr(mod.click, "confirm", fake_confirm)

    accounts = [GhAccount(login="example-user", active=True)]
    result = run_wizard(["claude_code", "codex"], accounts=accounts)
    assert result.agent_to_identity == {"claude_code": "example-user"}
    # codex was skipped, no entry in agent_to_identity
    assert "codex" not in result.agent_to_identity


# ---------------------------------------------------------------------------
# init integration — wizard skipped for non-TTY
# ---------------------------------------------------------------------------


def test_run_wizard_keychain_branch(monkeypatch: pytest.MonkeyPatch) -> None:
    """Selecting the keychain option writes gh_token_keychain to the binding
    and offers to store the token via keyring."""
    from agentshore import cli_identity as mod

    # Force keyring to look available so the wizard offers option 3.
    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: "macOS Keychain (TEST)")

    stored: dict[str, str] = {}

    def fake_set_password(service: str, username: str, token: str) -> None:
        stored[service] = token

    import keyring

    monkeypatch.setattr(keyring, "set_password", fake_set_password)

    # New flow: Pass 1 picks claude_code → 1; Pass 2 prompts email "",
    # name "", "Do you have a PAT?" → True (paste path), then paste
    # "ghp_secret" — stored in keychain at the default service.
    inputs = iter(["1", "", "", "ghp_secret"])
    confirms = iter([True])  # paste-PAT-now → yes

    def fake_prompt(msg: str, default: str | None = None, **_: object) -> str:
        try:
            value = next(inputs)
        except StopIteration as exc:
            raise AssertionError(f"unexpected prompt: {msg}") from exc
        return value or (default if default is not None else "")

    def fake_confirm(_msg: str, default: bool = False, **_kw: object) -> bool:
        try:
            return next(confirms)
        except StopIteration:
            return default

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    monkeypatch.setattr(mod.click, "confirm", fake_confirm)

    accounts = [GhAccount(login="example-user", active=True)]
    result = mod.run_wizard(["claude_code"], accounts=accounts)

    assert result.identities["example-user"].gh_token_keychain == "agentshore/example-user"
    assert result.identities["example-user"].gh_token_login is None
    assert result.identities["example-user"].gh_token_env is None
    assert stored == {"agentshore/example-user": "ghp_secret"}


def test_keychain_backend_label_when_no_backend(monkeypatch: pytest.MonkeyPatch) -> None:
    """If the active keyring backend is the fail backend, hide the keychain option."""
    import keyring
    from keyring.backends.fail import Keyring as FailKeyring

    from agentshore import cli_identity as mod

    monkeypatch.setattr(keyring, "get_keyring", lambda: FailKeyring())
    assert mod._keychain_backend_label() is None


def test_run_identity_wizard_skips_when_non_interactive(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from agentshore.cli_identity import run_identity_wizard

    # AGENTSHORE_NONINTERACTIVE forces the skip path.
    monkeypatch.setenv("AGENTSHORE_NONINTERACTIVE", "1")

    config_path = tmp_path / "agentshore.yaml"
    config_path.write_text(_BASE_YAML, encoding="utf-8")

    # Should print a message and return without touching the file.
    run_identity_wizard(config_path, ["claude_code", "codex"])

    # File unchanged.
    assert "identities" not in config_path.read_text(encoding="utf-8")


def test_run_identity_wizard_noninteractive_normalizes_existing_trusted_ids(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from agentshore.cli_identity import run_identity_wizard

    monkeypatch.setenv("AGENTSHORE_NONINTERACTIVE", "1")

    config_path = tmp_path / "agentshore.yaml"
    config_path.write_text(
        _BASE_YAML.replace(
            "  codex:\n    enabled: true\n    binary: codex",
            "  codex:\n    enabled: true\n    binary: codex\n    identity: unseriousai",
        )
        + """\
identities:
  unseriousai:
    git_user_name: "Unserious AI Bot"
    git_user_email: bot@example.com
    gh_token_env: UNSERIOUSAI_GH_TOKEN
trusted_ids:
  github_logins:
    - ExistingUser
""",
        encoding="utf-8",
    )

    run_identity_wizard(config_path, ["codex"], force_run=True)

    data = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    assert data["trusted_ids"]["github_logins"] == ["existinguser", "unseriousai"]


# ---------------------------------------------------------------------------
# `agentshore identity` CLI command
# ---------------------------------------------------------------------------


def test_agentshore_identity_prints_table_when_resolved(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from click.testing import CliRunner

    from agentshore.cli import main

    monkeypatch.setenv("UNSERIOUSAI_GH_TOKEN", "ghp_x")
    monkeypatch.setattr(
        "agentshore.agents.identity._validate_github_token",
        lambda _token: (True, "unseriousAI", None),
    )
    monkeypatch.setattr(
        "agentshore.agents.identity.report_identity_repo_access",
        lambda _cfg, _project: [],
    )
    yaml_text = (
        _BASE_YAML
        + """
identities:
  unseriousAI:
    git_user_name: "unseriousAI"
    git_user_email: "bot@example.com"
    gh_token_env: UNSERIOUSAI_GH_TOKEN
"""
    )
    # Add the agent->identity link manually.
    yaml_text = yaml_text.replace(
        "  codex:\n    enabled: true\n    binary: codex",
        "  codex:\n    enabled: true\n    binary: codex\n    identity: unseriousAI",
    )
    (tmp_path / "agentshore.yaml").write_text(yaml_text, encoding="utf-8")

    runner = CliRunner()
    result = runner.invoke(main, ["identity", "--project", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "codex" in result.output
    assert "unseriousAI" in result.output
    assert "token: ok" in result.output


def test_agentshore_identity_exits_nonzero_on_missing_token(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from click.testing import CliRunner

    from agentshore.cli import main

    monkeypatch.delenv("UNSERIOUSAI_GH_TOKEN", raising=False)
    yaml_text = (
        _BASE_YAML
        + """
identities:
  unseriousAI:
    git_user_name: "unseriousAI"
    git_user_email: "bot@example.com"
    gh_token_env: UNSERIOUSAI_GH_TOKEN
"""
    )
    yaml_text = yaml_text.replace(
        "  codex:\n    enabled: true\n    binary: codex",
        "  codex:\n    enabled: true\n    binary: codex\n    identity: unseriousAI",
    )
    (tmp_path / "agentshore.yaml").write_text(yaml_text, encoding="utf-8")

    runner = CliRunner()
    result = runner.invoke(main, ["identity", "--project", str(tmp_path)])
    assert result.exit_code == 1
    assert "MISSING" in result.output


def test_agentshore_identity_prints_repo_access_when_available(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from click.testing import CliRunner

    from agentshore.agents.identity import RepoAccessStatus
    from agentshore.cli import main

    monkeypatch.setenv("UNSERIOUSAI_GH_TOKEN", "ghp_x")
    monkeypatch.setattr(
        "agentshore.agents.identity._validate_github_token",
        lambda _token: (True, "unseriousAI", None),
    )
    monkeypatch.setattr(
        "agentshore.agents.identity.report_identity_repo_access",
        lambda _cfg, _project: [
            RepoAccessStatus(
                agent_key="codex",
                identity_name="unseriousai",
                ok=True,
                detail="ok",
            )
        ],
    )
    yaml_text = (
        _BASE_YAML.replace(
            "  codex:\n    enabled: true\n    binary: codex",
            "  codex:\n    enabled: true\n    binary: codex\n    identity: unseriousai",
        )
        + """
identities:
  unseriousai:
    git_user_name: "Unserious AI Bot"
    git_user_email: "bot@example.com"
    gh_token_env: UNSERIOUSAI_GH_TOKEN
"""
    )
    (tmp_path / "agentshore.yaml").write_text(yaml_text, encoding="utf-8")

    result = CliRunner().invoke(main, ["identity", "--project", str(tmp_path)])

    assert result.exit_code == 0, result.output
    assert "Repository access" in result.output
    assert "codex" in result.output
    assert "[repo: ok]" in result.output


def test_agentshore_identity_exits_nonzero_on_repo_access_block(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from click.testing import CliRunner

    from agentshore.agents.identity import RepoAccessStatus
    from agentshore.cli import main

    monkeypatch.setenv("UNSERIOUSAI_GH_TOKEN", "ghp_x")
    monkeypatch.setattr(
        "agentshore.agents.identity._validate_github_token",
        lambda _token: (True, "unseriousAI", None),
    )
    monkeypatch.setattr(
        "agentshore.agents.identity.report_identity_repo_access",
        lambda _cfg, _project: [
            RepoAccessStatus(
                agent_key="codex",
                identity_name="unseriousai",
                ok=False,
                detail="GraphQL: Could not resolve to a Repository",
            )
        ],
    )
    yaml_text = (
        _BASE_YAML.replace(
            "  codex:\n    enabled: true\n    binary: codex",
            "  codex:\n    enabled: true\n    binary: codex\n    identity: unseriousai",
        )
        + """
identities:
  unseriousai:
    git_user_name: "Unserious AI Bot"
    git_user_email: "bot@example.com"
    gh_token_env: UNSERIOUSAI_GH_TOKEN
"""
    )
    (tmp_path / "agentshore.yaml").write_text(yaml_text, encoding="utf-8")

    result = CliRunner().invoke(main, ["identity", "--project", str(tmp_path)])

    assert result.exit_code == 1
    assert "Repository access" in result.output
    assert "[repo: BLOCKED" in result.output
    assert "Could not resolve" in result.output


# ---------------------------------------------------------------------------
# _prompt_choice — re-prompt on garbage, max-attempts abort, extra keys
# ---------------------------------------------------------------------------


def test_prompt_choice_reprompts_on_garbage(monkeypatch: pytest.MonkeyPatch) -> None:
    """Non-numeric input that isn't an extra key re-prompts instead of
    silently falling back to the default option."""
    from agentshore import cli_identity as mod

    inputs = iter(["unseriousai", "2"])

    def fake_prompt(_msg: str, default: str | None = None, **_kw: object) -> str:
        try:
            return next(inputs)
        except StopIteration as exc:
            raise AssertionError("unexpected prompt") from exc

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    chosen = mod._prompt_choice("agent", ["example-user", "unseriousAI"], 0)
    assert chosen == "unseriousAI"


def test_prompt_choice_returns_extra_sentinel(monkeypatch: pytest.MonkeyPatch) -> None:
    from agentshore import cli_identity as mod

    inputs = iter(["n"])

    def fake_prompt(_msg: str, default: str | None = None, **_kw: object) -> str:
        return next(inputs)

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    chosen = mod._prompt_choice("agent", ["example-user"], 0, extra_keys={"n": "new account"})
    assert chosen == f"{mod._EXTRA_PREFIX}n"


def test_prompt_choice_max_attempts_raises_abort(monkeypatch: pytest.MonkeyPatch) -> None:
    from agentshore import cli_identity as mod

    # Five garbage inputs exhaust max_attempts=5.
    inputs = iter(["x"] * 6)

    def fake_prompt(_msg: str, default: str | None = None, **_kw: object) -> str:
        return next(inputs)

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    import pytest as _pytest

    with _pytest.raises(mod._WizardAbortError):
        mod._prompt_choice("agent", ["example-user"], 0)


# ---------------------------------------------------------------------------
# _prompt_new_login — validation, duplicates, back-out
# ---------------------------------------------------------------------------


def test_prompt_new_login_accepts_valid(monkeypatch: pytest.MonkeyPatch) -> None:
    from agentshore import cli_identity as mod

    inputs = iter(["unseriousai-bot"])
    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: next(inputs))
    assert mod._prompt_new_login(set()) == "unseriousai-bot"


def test_prompt_new_login_rejects_invalid_format(monkeypatch: pytest.MonkeyPatch) -> None:
    from agentshore import cli_identity as mod

    bad_inputs = ["", "_bad", "-leading", "trailing-", "a--b", "a" * 40]
    inputs = iter([*bad_inputs, "valid"])
    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: next(inputs))
    # max_attempts=20 to absorb every bad input plus the final good one.
    assert mod._prompt_new_login(set(), max_attempts=20) == "valid"


def test_prompt_new_login_rejects_duplicate_case_insensitive(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A case-insensitive match against existing logins returns the
    canonical existing spelling rather than re-prompting."""
    from agentshore import cli_identity as mod

    inputs = iter(["EXAMPLE-USER"])
    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: next(inputs))
    assert mod._prompt_new_login({"example-user"}) == "example-user"


def test_prompt_new_login_back_out(monkeypatch: pytest.MonkeyPatch) -> None:
    from agentshore import cli_identity as mod

    inputs = iter(["s"])
    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: next(inputs))
    assert mod._prompt_new_login(set()) is None


# ---------------------------------------------------------------------------
# run_wizard — new-account path, two-pass detail prompts
# ---------------------------------------------------------------------------


def test_run_wizard_new_account_path(monkeypatch: pytest.MonkeyPatch) -> None:
    """User picks (n) for codex, types a new login; pass-2 details fire
    for both example-user and the new account, with env-var as the default
    token strategy for the new account."""
    from agentshore import cli_identity as mod

    # Pass 1: claude_code → 1 (example-user), codex → n then "newbot".
    # Pass 2: example-user details (email, name, strategy=1 gh_login),
    #         newbot details (email, name, strategy default Enter → "2"
    #                          env var, then env var name "").
    inputs = iter(
        [
            "1",
            "n",
            "newbot",  # pass 1
            "",
            "",
            "1",  # example-user details
            "",
            "",
            "",
            "",  # newbot details (Enter for email, name,
            #  strategy=default-which-is-2, env-var name)
        ]
    )

    def fake_prompt(msg: str, default: str | None = None, **_kw: object) -> str:
        try:
            value = next(inputs)
        except StopIteration as exc:
            raise AssertionError(f"unexpected prompt: {msg}") from exc
        return value or (default if default is not None else "")

    monkeypatch.setattr(mod, "_keychain_has_token", lambda _service: False)
    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    monkeypatch.setattr(mod.click, "confirm", lambda *_a, **_k: False)

    accounts = [GhAccount(login="example-user", active=True)]
    result = run_wizard(["claude_code", "codex"], accounts=accounts)

    assert result.agent_to_identity == {
        "claude_code": "example-user",
        "codex": "newbot",
    }
    assert result.identities["example-user"].gh_token_login == "example-user"
    # New account defaults to env strategy (gh_token_env set, gh_token_login None).
    assert result.identities["newbot"].gh_token_env == "NEWBOT_GH_TOKEN"
    assert result.identities["newbot"].gh_token_login is None


def test_prompt_token_strategy_warns_and_reprompts_on_gh_login_for_new_account(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """User declines paste-PAT, picks gh_login (1) from the strategy menu,
    declines the use-anyway confirm, is asked to pick again, picks env (2).
    Final binding is env-strategy."""
    from agentshore import cli_identity as mod

    # Force keyring backend visible so the paste-PAT prompt fires.
    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: "Test backend")
    monkeypatch.setattr(mod, "_keychain_has_token", lambda _service: False)
    inputs = iter(["1", "2", ""])  # strategy pick 1, then pick 2, then env var name default
    confirms = iter([False, False])  # decline paste-PAT, decline use-gh-login-anyway

    def fake_prompt(_msg: str, default: str | None = None, **_kw: object) -> str:
        value = next(inputs)
        return value or (default if default is not None else "")

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    monkeypatch.setattr(mod.click, "confirm", lambda *_a, **_k: next(confirms))

    strategy, fields = mod._prompt_token_strategy("newbot", is_new_account=True)
    assert strategy == "env"
    assert fields == {"gh_token_env": "NEWBOT_GH_TOKEN"}


def test_prompt_token_strategy_accepts_gh_login_for_new_account_when_confirmed(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """User declines paste-PAT, picks gh_login (1) from the strategy menu,
    confirms the use-anyway prompt. Binding records gh_token_login."""
    from agentshore import cli_identity as mod

    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: "Test backend")
    monkeypatch.setattr(mod, "_keychain_has_token", lambda _service: False)
    inputs = iter(["1"])
    confirms = iter([False, True])  # decline paste-PAT, accept gh_login risk

    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: next(inputs))
    monkeypatch.setattr(mod.click, "confirm", lambda *_a, **_k: next(confirms))

    strategy, fields = mod._prompt_token_strategy("newbot", is_new_account=True)
    assert strategy == "gh_login"
    assert fields == {"gh_token_login": "newbot"}


def test_prompt_token_strategy_paste_pat_stores_in_keychain(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Happy path: user accepts the paste-PAT prompt, pastes a real-looking
    PAT, and the wizard stores it under agentshore/<login> with no env var
    name ever requested."""
    from agentshore import cli_identity as mod

    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: "Test backend")
    monkeypatch.setattr(mod, "_keychain_has_token", lambda _service: False)
    stored: dict[str, str] = {}
    monkeypatch.setattr(
        "keyring.set_password",
        lambda service, _user, token: stored.__setitem__(service, token),
    )

    inputs = iter(["ghp_realtoken12345"])
    confirms = iter([True])  # accept paste-PAT

    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: next(inputs))
    monkeypatch.setattr(mod.click, "confirm", lambda *_a, **_k: next(confirms))

    strategy, fields = mod._prompt_token_strategy("newbot", is_new_account=True)
    assert strategy == "keychain"
    assert fields == {"gh_token_keychain": "agentshore/newbot"}
    assert stored == {"agentshore/newbot": "ghp_realtoken12345"}


def test_prompt_token_strategy_paste_pat_stores_repo_specific_keychain(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Repo-aware wizard runs store pasted PATs under agentshore/owner/repo/login."""
    from agentshore import cli_identity as mod

    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: "Test backend")
    monkeypatch.setattr(mod, "_keychain_has_token", lambda _service: False)
    stored: dict[str, str] = {}
    monkeypatch.setattr(
        "keyring.set_password",
        lambda service, _user, token: stored.__setitem__(service, token),
    )

    inputs = iter(["ghp_realtoken12345"])
    confirms = iter([True])  # accept paste-PAT

    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: next(inputs))
    monkeypatch.setattr(mod.click, "confirm", lambda *_a, **_k: next(confirms))

    strategy, fields = mod._prompt_token_strategy(
        "unseriousAI",
        is_new_account=True,
        repo_name_with_owner="example-user/example-repo",
    )

    assert strategy == "keychain"
    assert fields == {"gh_token_keychain": "agentshore/example-user/example-repo/unseriousai"}
    assert stored == {"agentshore/example-user/example-repo/unseriousai": "ghp_realtoken12345"}


def test_prompt_token_strategy_keychain_service_uses_lowercase_login(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Keychain services use canonical lowercase identity names even when
    GitHub's display login has mixed case."""
    from agentshore import cli_identity as mod

    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: "Test backend")
    monkeypatch.setattr(mod, "_keychain_has_token", lambda _service: False)
    stored: dict[str, str] = {}
    monkeypatch.setattr(
        "keyring.set_password",
        lambda service, _user, token: stored.__setitem__(service, token),
    )
    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: "ghp_realtoken12345")
    monkeypatch.setattr(mod.click, "confirm", lambda *_a, **_k: True)

    strategy, fields = mod._prompt_token_strategy("unseriousAI", is_new_account=True)
    assert strategy == "keychain"
    assert fields == {"gh_token_keychain": "agentshore/unseriousai"}
    assert stored == {"agentshore/unseriousai": "ghp_realtoken12345"}


def test_run_wizard_replaces_agentshore_global_keychain_with_repo_service(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Existing agentshore/<login> bindings are auto-migrated to repo-scoped service."""
    from unittest.mock import patch

    existing = {
        "unseriousAI": IdentityBinding(
            name="unseriousAI",
            git_user_name="UnseriousAI",
            git_user_email="bot@example.com",
            gh_token_keychain="agentshore/unseriousAI",
        )
    }

    with (
        patch("agentshore.cli_identity._prompt_choice", return_value="unseriousai"),
        patch("agentshore.cli_identity._migrate_keychain_token", return_value=True) as mock_migrate,
    ):
        result = run_wizard(
            ["codex"],
            accounts=[GhAccount(login="example-user", active=True)],
            defaults={"codex": "unseriousAI"},
            existing_identities=existing,
            repo_name_with_owner="example-user/example-repo",
        )

    mock_migrate.assert_called_once_with(
        "agentshore/unseriousai",
        "agentshore/example-user/example-repo/unseriousai",
    )
    assert result.identities["unseriousai"].gh_token_keychain == (
        "agentshore/example-user/example-repo/unseriousai"
    )
    assert result.identities["unseriousai"].git_user_name == "UnseriousAI"


def test_prompt_token_strategy_uses_existing_keychain_token(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """If agentshore/<login> already has a token, the wizard offers that
    binding directly and does not ask the user to paste the PAT again."""
    from agentshore import cli_identity as mod

    confirm_calls: list[tuple[tuple[object, ...], dict[str, object]]] = []

    def fake_confirm(*args: object, **kwargs: object) -> bool:
        confirm_calls.append((args, kwargs))
        return True

    def fail_prompt(*args: object, **kwargs: object) -> str:
        raise AssertionError(f"unexpected prompt: {args}, {kwargs}")

    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: "Test backend")
    monkeypatch.setattr(
        mod,
        "_keychain_has_token",
        lambda service: service == "agentshore/unseriousai",
    )
    monkeypatch.setattr(mod.click, "confirm", fake_confirm)
    monkeypatch.setattr(mod.click, "prompt", fail_prompt)

    strategy, fields = mod._prompt_token_strategy("unseriousai", is_new_account=True)

    assert strategy == "keychain"
    assert fields == {"gh_token_keychain": "agentshore/unseriousai"}
    assert len(confirm_calls) == 1
    assert "Use the existing keychain token" in str(confirm_calls[0][0][0])
    assert confirm_calls[0][1]["default"] is True


def test_prompt_token_strategy_declining_existing_keychain_falls_through(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Declining the existing keychain token leaves it untouched and still
    allows the normal strategy menu."""
    from agentshore import cli_identity as mod

    confirm_values = iter([False, False])  # decline existing token, decline paste-PAT
    inputs = iter(["2", ""])

    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: "Test backend")
    monkeypatch.setattr(mod, "_keychain_has_token", lambda _service: True)
    monkeypatch.setattr(mod.click, "confirm", lambda *_a, **_kw: next(confirm_values))

    def fake_prompt(_msg: str, default: str | None = None, **_kw: object) -> str:
        value = next(inputs)
        return value or (default if default is not None else "")

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)

    strategy, fields = mod._prompt_token_strategy("unseriousai", is_new_account=True)

    assert strategy == "env"
    assert fields == {"gh_token_env": "UNSERIOUSAI_GH_TOKEN"}


def test_prompt_env_var_name_rejects_pat_shape(monkeypatch: pytest.MonkeyPatch) -> None:
    """User pastes a PAT into the env-var-NAME slot. Wizard rejects with a
    clear redirect message and re-prompts; eventually accepts a valid name."""
    from agentshore import cli_identity as mod

    inputs = iter(["ghp_realtoken12345", "github_pat_11A46VGFA0lE", "MY_GH_TOKEN"])
    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: next(inputs))
    name = mod._prompt_env_var_name("unseriousai")
    assert name == "MY_GH_TOKEN"


def test_prompt_env_var_name_rejects_invalid_shape(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Names with hyphens, leading digits, or empty re-prompt; valid wins."""
    from agentshore import cli_identity as mod

    inputs = iter(["MY-VAR", "1ABC", "", "VALID_NAME"])
    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: next(inputs))
    name = mod._prompt_env_var_name("login", max_attempts=10)
    assert name == "VALID_NAME"


def test_prompt_env_var_name_max_attempts_raises(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from agentshore import cli_identity as mod

    inputs = iter(["ghp_x"] * 10)
    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: next(inputs))
    import pytest as _pytest

    with _pytest.raises(mod._WizardAbortError):
        mod._prompt_env_var_name("login", max_attempts=3)


def test_looks_like_pat() -> None:
    from agentshore.cli_identity import looks_like_pat

    assert looks_like_pat("ghp_realtoken12345")
    assert looks_like_pat("github_pat_11A46VGFA0lE")
    assert looks_like_pat("gho_xxxxx")
    assert looks_like_pat("ghu_xxxxx")
    assert looks_like_pat("ghs_xxxxx")
    assert looks_like_pat("ghr_xxxxx")
    assert looks_like_pat("  ghp_with_whitespace  ")
    # Negatives
    assert not looks_like_pat("UNSERIOUSAI_GH_TOKEN")
    assert not looks_like_pat("MY_VAR")
    assert not looks_like_pat("")
    assert not looks_like_pat("agentshore/example-user")


def test_report_identities_redacts_pat_in_env_field(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Defensive: even if a PAT slipped into agentshore.yaml's gh_token_env
    field (legacy bug, hand-edit, etc.), the resolution report must NOT
    echo it. The token must be marked unresolved with a redaction message
    that names the field but never the value."""
    from agentshore.agents.identity import report_identities
    from agentshore.config.models import (
        AgentConfig,
        GitHubIdentity,
        RuntimeConfig,
    )

    leaked_pat = "ghp_thisIsTheLeakedToken12345"
    cfg = RuntimeConfig(
        identities={
            "unseriousai": GitHubIdentity(
                git_user_name="unseriousai",
                git_user_email="bot@example.com",
                gh_token_env=leaked_pat,
            )
        },
        agents={"codex": AgentConfig(identity="unseriousai")},
    )
    rows = report_identities(cfg)
    (row,) = rows
    assert row.token_resolved is False
    assert "REDACTED" in row.detail
    assert leaked_pat not in row.detail
    # Identity name and the suggested replacement are mentioned for guidance.
    assert "UNSERIOUSAI_GH_TOKEN" in row.detail


def test_echo_identity_report_format() -> None:
    """The report line collapses status + source into a single bracketed
    clause, replacing the old dual-column format."""
    from io import StringIO
    from unittest.mock import patch

    from agentshore.agents.identity import IdentityStatus
    from agentshore.cli_identity import echo_identity_report

    rows = [
        IdentityStatus(
            agent_key="claude_code",
            identity_name="example-user",
            token_source="gh_login",
            token_resolved=True,
            token_valid=True,
            detail="gh auth token -u example-user",
        ),
        IdentityStatus(
            agent_key="codex",
            identity_name="unseriousai",
            token_source="env",
            token_resolved=False,
            detail="env var UNSERIOUSAI_GH_TOKEN is unset",
        ),
    ]
    buf = StringIO()
    with patch("sys.stdout", buf):
        echo_identity_report(rows, header=False)
    text = buf.getvalue()
    assert "[token: ok via gh auth token -u example-user]" in text
    assert "[token: MISSING — env var UNSERIOUSAI_GH_TOKEN is unset]" in text


def test_run_identity_wizard_emits_verification_table(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """After patch_yaml_with_bindings, the wizard reloads the config and
    prints the resolution table inline. The user sees `[token: MISSING]`
    rows with the env var name they just chose."""
    from agentshore import cli_identity as mod
    from agentshore.cli_identity import run_identity_wizard

    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: None)  # no keychain
    monkeypatch.setattr("sys.stdin.isatty", lambda: True)
    monkeypatch.delenv("AGENTSHORE_NONINTERACTIVE", raising=False)

    # Pass 1: claude_code → 1 (example-user); Pass 2: email "", name "",
    # strategy 2 (env), env var name default → EXAMPLE_USER_GH_TOKEN.
    inputs = iter(["1", "", "", "2", ""])
    confirms = iter([False])  # decline paste-PAT (no keychain anyway)

    def fake_prompt(_msg: str, default: str | None = None, **_kw: object) -> str:
        value = next(inputs)
        return value or (default if default is not None else "")

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    monkeypatch.setattr(mod.click, "confirm", lambda *_a, **_k: next(confirms))
    monkeypatch.setattr(
        mod, "detect_gh_accounts", lambda: [GhAccount(login="example-user", active=True)]
    )

    cfg_path = tmp_path / "agentshore.yaml"
    cfg_path.write_text(_BASE_YAML, encoding="utf-8")

    # Capture echoed output.
    output: list[str] = []
    monkeypatch.setattr(mod.click, "echo", lambda msg="", **_kw: output.append(str(msg)))

    run_identity_wizard(cfg_path, ["claude_code"], force_run=True)

    joined = "\n".join(output)
    assert "Wrote identity bindings to" in joined
    assert "Identity bindings" in joined
    assert "[token: MISSING — env var EXAMPLE_USER_GH_TOKEN is unset]" in joined
    assert "export EXAMPLE_USER_GH_TOKEN=" in joined


def test_run_identity_wizard_post_report_includes_repo_access(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """After tokens validate, the init/reconfigure post-report also checks repo access."""
    from agentshore import cli_identity as mod
    from agentshore.agents.identity import RepoAccessStatus
    from agentshore.cli_identity import run_identity_wizard

    monkeypatch.setenv("EXAMPLE_USER_GH_TOKEN", "ghp_x")
    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: None)
    monkeypatch.setattr("sys.stdin.isatty", lambda: True)
    monkeypatch.delenv("AGENTSHORE_NONINTERACTIVE", raising=False)
    monkeypatch.setattr(
        "agentshore.agents.identity._validate_github_token",
        lambda _token: (True, "example-user", None),
    )
    monkeypatch.setattr(
        "agentshore.agents.identity.report_identity_repo_access",
        lambda _cfg, _project: [
            RepoAccessStatus(
                agent_key="claude_code",
                identity_name="example-user",
                ok=True,
                detail="ok",
            )
        ],
    )

    inputs = iter(["1", "", "", "2", ""])
    confirms = iter([False])

    def fake_prompt(_msg: str, default: str | None = None, **_kw: object) -> str:
        value = next(inputs)
        return value or (default if default is not None else "")

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    monkeypatch.setattr(mod.click, "confirm", lambda *_a, **_k: next(confirms))
    monkeypatch.setattr(
        mod, "detect_gh_accounts", lambda: [GhAccount(login="example-user", active=True)]
    )

    cfg_path = tmp_path / "agentshore.yaml"
    cfg_path.write_text(_BASE_YAML, encoding="utf-8")
    output: list[str] = []
    monkeypatch.setattr(mod.click, "echo", lambda msg="", **_kw: output.append(str(msg)))

    run_identity_wizard(cfg_path, ["claude_code"], force_run=True)

    joined = "\n".join(output)
    assert "Repository access" in joined
    assert "claude_code  →  example-user  [repo: ok]" in joined
    assert "All identity tokens resolve and can access the repository." in joined


def test_run_identity_wizard_post_report_fails_on_repo_access_block(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from agentshore import cli_identity as mod
    from agentshore.agents.identity import RepoAccessStatus
    from agentshore.cli_identity import run_identity_wizard

    monkeypatch.setenv("EXAMPLE_USER_GH_TOKEN", "ghp_x")
    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: None)
    monkeypatch.setattr("sys.stdin.isatty", lambda: True)
    monkeypatch.delenv("AGENTSHORE_NONINTERACTIVE", raising=False)
    monkeypatch.setattr(
        "agentshore.agents.identity._validate_github_token",
        lambda _token: (True, "example-user", None),
    )
    monkeypatch.setattr(
        "agentshore.agents.identity.report_identity_repo_access",
        lambda _cfg, _project: [
            RepoAccessStatus(
                agent_key="claude_code",
                identity_name="example-user",
                ok=False,
                detail="GraphQL: Could not resolve to a Repository",
            )
        ],
    )

    inputs = iter(["1", "", "", "2", ""])
    confirms = iter([False])

    def fake_prompt(_msg: str, default: str | None = None, **_kw: object) -> str:
        value = next(inputs)
        return value or (default if default is not None else "")

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    monkeypatch.setattr(mod.click, "confirm", lambda *_a, **_k: next(confirms))
    monkeypatch.setattr(
        mod, "detect_gh_accounts", lambda: [GhAccount(login="example-user", active=True)]
    )

    cfg_path = tmp_path / "agentshore.yaml"
    cfg_path.write_text(_BASE_YAML, encoding="utf-8")
    output: list[str] = []
    monkeypatch.setattr(mod.click, "echo", lambda msg="", **_kw: output.append(str(msg)))

    with pytest.raises(SystemExit):
        run_identity_wizard(cfg_path, ["claude_code"], force_run=True)

    joined = "\n".join(output)
    assert "Repository access" in joined
    assert "[repo: BLOCKED" in joined
    assert "cannot access this repository" in joined


def test_prompt_token_strategy_no_use_anyway_confirm_for_existing_account(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """For an existing gh-authed account picking gh_login does NOT prompt
    the are-you-sure use-anyway confirm. The paste-PAT confirm still fires
    once at the top of the flow (declined here) but use-anyway must not."""
    from agentshore import cli_identity as mod

    monkeypatch.setattr(mod, "_keychain_backend_label", lambda: "Test backend")
    inputs = iter(["1"])
    confirm_calls: list[tuple[object, ...]] = []

    def fake_confirm(*args: object, **_kw: object) -> bool:
        confirm_calls.append(args)
        return False  # decline whatever is asked

    monkeypatch.setattr(mod.click, "prompt", lambda *_a, **_k: next(inputs))
    monkeypatch.setattr(mod.click, "confirm", fake_confirm)

    strategy, fields = mod._prompt_token_strategy("example-user", is_new_account=False)
    assert strategy == "gh_login"
    assert fields == {"gh_token_login": "example-user"}
    # Exactly one confirm call: the paste-PAT prompt. No use-anyway confirm.
    assert len(confirm_calls) == 1
    assert "Do you have a PAT" in confirm_calls[0][0]


def test_run_wizard_shared_identity_prompts_details_once(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Two agents binding to the same identity: pass-2 fires once."""
    from agentshore import cli_identity as mod

    # Both agents → 1 (example-user). Pass 2: one detail block (email "",
    # name "", paste-PAT? → False default, strategy "1" → gh_login).
    inputs = iter(["1", "1", "", "", "1"])

    def fake_prompt(msg: str, default: str | None = None, **_kw: object) -> str:
        try:
            value = next(inputs)
        except StopIteration as exc:
            raise AssertionError(f"unexpected prompt: {msg}") from exc
        return value or (default if default is not None else "")

    monkeypatch.setattr(mod.click, "prompt", fake_prompt)
    monkeypatch.setattr(mod.click, "confirm", lambda *_a, **_k: False)

    accounts = [GhAccount(login="example-user", active=True)]
    result = run_wizard(["claude_code", "codex"], accounts=accounts)
    assert result.agent_to_identity == {
        "claude_code": "example-user",
        "codex": "example-user",
    }
    assert list(result.identities.keys()) == ["example-user"]


# ---------------------------------------------------------------------------
# run_identity_wizard — gating with force_run
# ---------------------------------------------------------------------------


def test_run_identity_wizard_force_run_non_tty(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """``force_run=True`` on a non-TTY prints the skip notice and leaves the
    yaml untouched (does not crash, does not silently no-op)."""
    from agentshore.cli_identity import run_identity_wizard

    monkeypatch.delenv("AGENTSHORE_NONINTERACTIVE", raising=False)
    monkeypatch.setattr("sys.stdin.isatty", lambda: False)

    config_path = tmp_path / "agentshore.yaml"
    config_path.write_text(_BASE_YAML, encoding="utf-8")
    run_identity_wizard(config_path, ["claude_code"], force_run=True)
    assert "identities" not in config_path.read_text(encoding="utf-8")
    assert "not a TTY" in capsys.readouterr().out


# ---------------------------------------------------------------------------
# _agent_keys_from_yaml — disabled-agent filter
# ---------------------------------------------------------------------------


def test_agent_keys_from_yaml_filters_disabled_and_api(tmp_path: Path) -> None:
    """``enabled: false`` agents and ``api_*`` agents are filtered out;
    missing ``enabled`` defaults to enabled."""
    from agentshore.cli import _agent_keys_from_yaml

    yaml_text = """\
agents:
  claude_code:
    enabled: true
    binary: claude
  codex:
    enabled: false
    binary: codex
  aider:
    binary: aider
  gemini:
    enabled: true
    binary: gemini
"""
    cfg_path = tmp_path / "agentshore.yaml"
    cfg_path.write_text(yaml_text, encoding="utf-8")
    keys = _agent_keys_from_yaml(cfg_path)
    assert "claude_code" in keys
    assert "aider" in keys
    assert "gemini" in keys
    assert "codex" not in keys  # explicitly disabled


# ---------------------------------------------------------------------------
# `agentshore identity --reconfigure`
# ---------------------------------------------------------------------------


def test_agentshore_identity_reconfigure_invokes_wizard_without_db_reset(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``agentshore identity --reconfigure`` re-runs the wizard (writes new
    bindings) and leaves an existing ``.agentshore/agentshore.db`` untouched."""
    from click.testing import CliRunner

    from agentshore.cli import main

    # Pre-existing agentshore.yaml and DB.
    cfg_path = tmp_path / "agentshore.yaml"
    cfg_path.write_text(_BASE_YAML, encoding="utf-8")
    agentshore_dir = tmp_path / ".agentshore"
    agentshore_dir.mkdir()
    db_path = agentshore_dir / "agentshore.db"
    db_path.write_bytes(b"sentinel-do-not-touch")
    db_mtime_before = db_path.stat().st_mtime_ns

    captured: dict[str, object] = {}

    def fake_run_wizard(
        config_path: Path,
        agent_keys: object,
        *,
        force_run: bool = False,
        defaults: dict[str, str] | None = None,
        existing_identities: object = None,
        repo_name_with_owner: str | None = None,
    ) -> None:
        captured["config_path"] = config_path
        captured["agent_keys"] = list(agent_keys)
        captured["force_run"] = force_run
        captured["defaults"] = defaults
        captured["repo_name_with_owner"] = repo_name_with_owner

    monkeypatch.setattr("agentshore.cli_identity.run_identity_wizard", fake_run_wizard)
    monkeypatch.setattr(
        "agentshore.cli._detect_gh_remote",
        lambda _project: {"nameWithOwner": "example-user/example-repo"},
    )

    runner = CliRunner()
    result = runner.invoke(main, ["identity", "--project", str(tmp_path), "--reconfigure"])
    assert result.exit_code == 0, result.output
    assert captured["config_path"] == cfg_path
    assert captured["agent_keys"] == ["claude_code", "codex"]
    assert captured["force_run"] is True
    # DB file untouched.
    assert captured["repo_name_with_owner"] == "example-user/example-repo"
    assert db_path.read_bytes() == b"sentinel-do-not-touch"
    assert db_path.stat().st_mtime_ns == db_mtime_before


def test_agentshore_init_passes_force_run(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """``agentshore init`` must invoke the wizard with ``force_run=True`` so the
    TTY heuristic doesn't silently skip an explicit user invocation."""
    from click.testing import CliRunner

    from agentshore.cli import main

    # Stub everything that init does *besides* the wizard.
    monkeypatch.setattr("agentshore.skills.install_skills", lambda *_a, **_k: [])
    captured: dict[str, object] = {}

    def fake_run_wizard(
        config_path: Path,
        agent_keys: object,
        *,
        force_run: bool = False,
        defaults: dict[str, str] | None = None,
        existing_identities: object = None,
        repo_name_with_owner: str | None = None,
    ) -> None:
        captured["force_run"] = force_run

    monkeypatch.setattr("agentshore.cli_identity.run_identity_wizard", fake_run_wizard)

    runner = CliRunner()
    # init wants `--project` to exist.
    result = runner.invoke(main, ["init", "--project", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert captured.get("force_run") is True
